export const config = {
    runtime: 'edge', 
};

export default async function handler(req) {
    if (req.method !== 'POST') return new Response('Method not allowed', { status: 405 });

    try {
        const { messages, modelId } = await req.json();
        const userQuery = messages[messages.length - 1].content;

        const GROQ_KEY = process.env.GROQ_API_KEY;
        const TAVILY_KEY = process.env.TAVILY_API_KEY;
        const GEMINI_KEY = process.env.GEMINI_API_KEY_3 || process.env.GEMINI_API_KEY_2 || process.env.GEMINI_API_KEY_1;

        let contextData = "";
        let systemPrompt = `You are Chatini, a premium, hyper-intelligent AI.
1. Answer directly, deeply, and accurately. ZERO hallucinations.
2. If the user asks for data, statistics, comparisons, or metrics, YOU MUST generate a JSON array and wrap it exactly in <chart>...</chart> tags to trigger the UI engine. 
Example Format: <chart>[{"label":"Category A", "value":85}, {"label":"Category B", "value":42}]</chart>
3. Ensure all chart data is REAL, mathematically sound, and generated by your analysis.`;

        // ---------------------------------------------------------
        // PASS 1: TAVILY DEEP SEARCH (Fail-Safe Wrapped)
        // ---------------------------------------------------------
        if ((modelId === 'flux' || modelId === 'oracle') && TAVILY_KEY) {
            try {
                const tavilyRes = await fetch('https://api.tavily.com/search', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        api_key: TAVILY_KEY,
                        query: userQuery,
                        search_depth: "advanced",
                        max_results: modelId === 'oracle' ? 20 : 5,
                        include_answer: true
                    })
                });
                
                if (tavilyRes.ok) {
                    const tavData = await tavilyRes.json();
                    contextData = `\n\n--- REAL-TIME SEARCH CONTEXT ---\n${tavData.results.map(r => r.content).join('\n')}`;
                    systemPrompt += `\n4. Synthesize the provided REAL-TIME SEARCH CONTEXT into your final answer.`;
                }
            } catch (e) {
                console.error("Tavily Search Failed, proceeding without context.");
            }
        }

        const processedMessages = [...messages];
        if (contextData) {
            processedMessages[processedMessages.length - 1].content += contextData;
        }

        // ---------------------------------------------------------
        // PASS 2: LLM STREAMING
        // ---------------------------------------------------------
        let streamUrl, headers, payload;

        if (modelId === 'spark') {
            // Groq Llama 3.1
            streamUrl = 'https://api.groq.com/openai/v1/chat/completions';
            headers = { 'Authorization': `Bearer ${GROQ_KEY}`, 'Content-Type': 'application/json' };
            payload = {
                model: 'llama-3.1-8b-instant',
                messages: [{ role: 'system', content: systemPrompt }, ...processedMessages],
                stream: true,
                temperature: 0.2
            };
        } else {
            // Gemini 2.5 Flash
            streamUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:streamGenerateContent?alt=sse&key=${GEMINI_KEY}`;
            headers = { 'Content-Type': 'application/json' };
            
            const geminiMessages = processedMessages.map(m => ({
                role: m.role === 'user' ? 'user' : 'model',
                parts: [{ text: m.content }]
            }));

            payload = {
                systemInstruction: { parts: [{ text: systemPrompt }] },
                contents: geminiMessages
            };
        }

        const llmRes = await fetch(streamUrl, { method: 'POST', headers, body: JSON.stringify(payload) });

        // IMPORTANT ERROR INTERCEPTOR
        // If API fails (e.g., Free Tier limit), stream the exact error back to UI
        if (!llmRes.ok) {
            const errorText = await llmRes.text();
            const errorStream = `data: ${JSON.stringify({ ui_error: `[API Blocked: ${llmRes.status}] ${errorText.substring(0, 150)}` })}\n\n`;
            return new Response(errorStream, { headers: { 'Content-Type': 'text/event-stream' } });
        }

        return new Response(llmRes.body, {
            headers: {
                'Content-Type': 'text/event-stream',
                'Cache-Control': 'no-cache',
                'Connection': 'keep-alive',
            },
        });

    } catch (error) {
        const errorStream = `data: ${JSON.stringify({ ui_error: `[Edge Error] ${error.message}` })}\n\n`;
        return new Response(errorStream, { headers: { 'Content-Type': 'text/event-stream' } });
    }
}


